os: linux
language: node_js
node_js:
  - 13
services:
  - postgresql
before_script:
  - psql -c 'create database healthy_test;' -U postgres

script:
  - node server.js &
  - npm test

env:
  - NODE_ENV_TYPE=test
